
---
- name: Backup System Configuration
  hosts: Linux
  tasks:
  - name: Create Directories for Backups
    file:
      path: /tmp/config_backup/
      state: directory
      mode: '0700'

  - name: Backup /etc Directory
    archive:
      path: /etc
      dest: /tmp/config_backup/{{ ansible_hostname }}-etc.tgz

  - name: Backup Network Interface Info
    shell: ip a &gt; /tmp/config_backup/interface-config.txt

  - name: Backup Routing Table
    shell: ip route &gt; /tmp/config_backup/route-config.txt

  - name: Backup Filesystem Sizes
    shell: df -hP &gt; /tmp/config_backup/df-output.txt

  - name: Backup lsblk --fs Info
    shell: lsblk --fs &gt; /tmp/config_backup/lsblk-config.txt

  - name: Backup TAR Directory
    archive:
      path: /tmp/config_backup
      dest: /tmp/{{ ansible_hostname }}_config_backup.tgz

  - name: Copy Configs to Centralized Location
    fetch:
      src: /tmp/{{ ansible_hostname }}_config_backup.tgz
      dest: /tmp/ansible_backups/{{ ansible_hostname }}/
      flat: yes
